### ISSUE TITLE
ERROR: name 'clip_model' is not defined

### ISSUE THREAD

**Issue by davidbejarcaceres** [aicrumb/doohickey#1]
I just opened the Colab verison today and this error appeared, maybe because of the [latest commit  ](https://github.com/aicrumb/doohickey/commit/88ddb8e7704e980e92448944f8fa0180cf5d96e3).

The Error:
![image](https://user-images.githubusercontent.com/17320214/190896103-044efc08-4c72-49db-87c8-66f58d9e1a46.png)

The params used for image generation:
![image](https://user-images.githubusercontent.com/17320214/190896151-06750534-edc7-4a2b-9e56-f1f6aa956d30.png)
![image](https://user-images.githubusercontent.com/17320214/190896167-a1134fbf-3f84-4892-bda2-3bc2a0e96c5d.png)

**Comment by aicrumb** [comment]
hey! I'm this is because your `loss_scale` is set to 0, but there's still a `clip_text_prompt`. Setting loss scale to anything other than 0 should fix this. (I would recommend 1-2.0)

I will make this (hopefully) not able to happen in an update soon.
